
CREATE DATABASE IF NOT EXISTS notes_db;
USE notes_db;
CREATE TABLE IF NOT EXISTS notes 
(
    ID INT NOT NULL AUTO_INCREMENT,
    Content TEXT,
    Completed BOOLEAN DEFAULT false,
    PRIMARY KEY(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
