apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: dXNlcl9wYXNzd29yZA== 
  mysql-database: dGVzdERi 
  mysql-user: dXNlcm5hbWU= 
  mysql-password: cGFzc3dvcmQ= 
